# Generated by Django 4.2.7 on 2023-12-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="VideoForm",),
    ]
