# Generated by Django 4.2.7 on 2024-01-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0006_alter_videoform_video"),
    ]

    operations = [
        migrations.DeleteModel(name="VideoForm",),
    ]
