# Generated by Django 4.2.7 on 2024-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("youtubepages", "0007_delete_videoform"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search", models.CharField(max_length=300)),
            ],
            options={"db_table": "UserSearch",},
        ),
    ]
