# Generated by Django 4.2.7 on 2024-01-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0008_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CategoryId", models.CharField(max_length=30)),
                ("Category", models.CharField(max_length=30)),
                ("ChannelName", models.CharField(max_length=80)),
                ("Title", models.CharField(max_length=200)),
                ("video", models.FileField(null=True, upload_to="", verbose_name="")),
            ],
            options={"db_table": "YoutubeVideo",},
        ),
    ]
