# Generated by Django 4.2.7 on 2024-01-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0011_delete_createuserform"),
    ]

    operations = [
        migrations.CreateModel(
            name="createuserForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("EmailId", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=20)),
                ("Gender", models.CharField(max_length=10)),
                ("ChannelName", models.TextField(max_length=60)),
                ("ProfileImage", models.FileField(upload_to="")),
            ],
            options={"db_table": "UserDetails",},
        ),
    ]
