# Generated by Django 4.2.7 on 2024-01-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0014_createusersform"),
    ]

    operations = [
        migrations.DeleteModel(name="createusersForm",),
    ]
