# Generated by Django 4.2.7 on 2024-01-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0016_createuserform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuserform",
            name="ProfileImage",
            field=models.FileField(null=True, upload_to="", verbose_name=""),
        ),
    ]
