# Generated by Django 4.2.7 on 2024-01-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0017_alter_createuserform_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createuserform",
            name="ProfileImage",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
