# Generated by Django 4.2.7 on 2024-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubepages", "0018_alter_createuserform_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="createuserform",
            name="Search",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
